- id: doi:10.1101/2023.09.04.556195
  my_comment: Schizosaccharomyces japonicus T2T preprint, 2023 
  publisher: bioRxiv
  image: https://www.biorxiv.org/content/biorxiv/early/2023/09/19/2023.09.04.556195/F1.large.jpg
  tags:
   - genome assembly
   - fission yeast

- id: doi:10.1002/yea.3919
  my_comment: Schizosaccharomyces versatilis, 2023
  image: https://www.biorxiv.org/content/biorxiv/early/2023/09/19/2023.09.04.556188/F6.large.jpg
  tags:
   - genome assembly
   - fission yeast

- id: doi:10.1016/j.cell.2023.10.015
  my_comment: Cell, 2023, neoChr paper
  image: https://www.cell.com/cms/attachment/431d7796-8b2c-404d-b54a-e1ea57864d8b/fx1.jpg
  tags:
   - budding yeast
   - synthetic biology

- id: doi:10.1128/mbio.01777-22
  my_comment: paper with Wolfe & Butler on Candida parapsilosis, 2022
  image: https://journals.asm.org/cms/10.1128/mbio.01777-22/asset/5ff8ad2e-f350-4ebb-9812-3d3e1ff24e5a/assets/images/medium/mbio.01777-22-f003.gif

- id: doi:10.1103/PhysRevE.103.052410
  my_comments: PRE paper with RR, 2021
  image: https://journals.aps.org/pre/article/10.1103/PhysRevE.103.052410/figures/1/medium
  tags:
   - mathematical modelling

- id: doi:10.1016/j.jbc.2021.100533
  my_comment: JBC paper with Rob, 2021
  image: https://www.jbc.org/cms/attachment/86f83300-193f-491f-b677-0de2f5c21c2f/gr1.jpg
  tags:
   - budding yeast
   
- id: doi:10.1073/pnas.2004664117
  my_comment: PNAS paper with CAF, 2020
  description: [H1 recommended](https://connect.h1.co/pubmed/32513739).
  image: https://www.pnas.org/cms/10.1073/pnas.2004664117/asset/fdb82a8b-cb06-4c3a-a9aa-d0395f97257f/assets/graphic/pnas.2004664117fig01.jpeg
  tags:
   - budding yeast

- id: doi:10.1371/journal.pcbi.1007651
  my_comment: Beacon calculus paper, 2020
  image: https://journals.plos.org/ploscompbiol/article/figure/image?size=large&id=10.1371/journal.pcbi.1007651.g001
  tags:
   - mathematical modelling

- id: doi:10.1038/s41596-019-0287-7
  my_comment: protocol paper, 2020
  description: During S phase, the relative DNA copy number increases for each region as it is replicated. Therefore, measuring DNA copy number can be used as a proxy for replication time. Here we present a step-by-step protocol to determine genome replication dynamics using high-throughput DNA sequencing to measure DNA copy-number. Cell populations can be obtained in three variants of the method sort-seq, sync-seq and MFA-seq.<br>We have shared our computational pipeline and example sequence data - see the [resources page](/DNA-replication-group-website/resources).
  image: https://media.springernature.com/m312/springer-static/image/art%3A10.1038%2Fs41596-019-0287-7/MediaObjects/41596_2019_287_Fig1_HTML.png
  tags:
   - new method
   - budding yeast

- id: doi:10.1186/s13059-019-1719-y
  my_comment: single cell review, 2019
  image: https://media.springernature.com/full/springer-static/image/art%3A10.1186%2Fs13059-019-1719-y/MediaObjects/13059_2019_1719_Fig1_HTML.png
  tags:
  - review

- id: doi:10.1038/s41467-019-09824-4
  my_comment: fission yeast centromeres with Robin, 2019
  description: [H1 recommended](https://connect.h1.co/pubmed/31138803).
  image: https://media.springernature.com/lw685/springer-static/image/art%3A10.1038%2Fs41467-019-09824-4/MediaObjects/41467_2019_9824_Fig1_HTML.png
  tags:
  - genome assembly
  - fission yeast

- id: doi:10.1038/s41592-019-0394-y
  my_comment: Nat Methods DNAscent paper, 2019
  description: DNA replication initiation is stochastic and obscured in population datasets. In this paper we introduce D-NAscent, a method to detect base analogs in ultra-long nanopore sequencing reads. This allowed us to identify replication origins and replication fork movement genome-wide on sequence reads of 20–160 kilobases. Our study marks the first, whole genome characterisation of DNA replication dynamics on single-molecules.<br>We have shared both the D-NAscent software and underlying sequence data - see the [resources page](/DNA-replication-group-website/resources).<br>[H1 recommended](https://connect.h1.co/pubmed/31011185).
  image: https://media.springernature.com/m312/springer-static/image/art%3A10.1038%2Fs41592-019-0394-y/MediaObjects/41592_2019_394_Fig1_HTML.png
  tags:
   - new method
   - nanopore
   - DNAscent
   - budding yeast

- id: doi:10.3390/genes10030196
  my_comment: cohesion paper, 2019
  description: In this study we address the long-standing question - do topologically associating domains (TADs) act as a causative organizing structure for replication timing domains? Using rapid and complete cohesin degradation we observe no perturbations to replication timing. Our results suggest that cohesin-mediated genome architecture is not required for replication timing patterns.
  image: https://www.mdpi.com/genes/genes-10-00196/article_deploy/html/images/genes-10-00196-g003.png
  tags:
  - cultured mammalian cells

- id: doi:10.1093/nar/gky590
  my_comment: ddPCR method paper, 2018
  description: In this paper we describe the use of digital PCR to precisely and rapidly measure DNA copy number as a proxy for replication time. As a proof-of-principle we demonstrate the method’s utility for the study of DNA replication time in both yeast and human cells. We show the power of the method by undertaking a targeted screen of kinetochore mutants to discover those that affect centromere replication time.  As part of this work we generated whole genome DNA replication timing data (sort-seq) for cultured human cells (HeLa).<br>These data can be visualised via the link to our UCSC genome browser hub on the [resources page](/DNA-replication-group-website/resources).
  image: images/ddPCR.png
  tags:
  - new method
  - budding yeast
  - cultured mammalian cells

- id:  doi:10.1093/molbev/msy075
  my_comment: Dasha's Hv paper, 2018
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/mbe/35/8/10.1093_molbev_msy075/1/m_msy075f1.jpeg?Expires=1704203197&Signature=i~VOUVUABJZf9DpsMU2Fzj3uD-9bibQ1qmBlnyB9rRhnG3xCLYH99NYkBmCxQikCJQVM~HppBw102hf5lJftUOV9HeMa5NCKCUN5zM8YUQHENanAKajNHsDmup054dzzWYyjJuPT1m3E7nGgQ3ujRLew-6IKlvr-xnG1hzboZUyERY2boVLAlzmAZEcv~jhS4w4ZE9s9~AKiE6RWNnPcLhqSI7rTFqmimex-U988JKo6j9y-3-jRNXKRT6DpO95lHFVnhTicgJxF1MTzpcHVoLn59mzojTOxsdg79eQW-ebN2hgjNTJIOHuSN-r9gs0VOFrhyDyQgLwetyrVRiP4JQ__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
  - archaea

- id: doi:10.12688/wellcomeopenres.13884.1
  my_comment: Ana's RTS1 paper, 2018
  tags:
  - budding yeast

- id: doi:10.1093/nar/gky132
  my_comment: RIF1 with Anne, 2018
  image: https://oup.silverchair-cdn.com/oup/backfile/Content_public/Journal/nar/46/8/10.1093_nar_gky132/1/m_gky132fig5.jpeg?Expires=1703041140&Signature=gW5IWf0r3K42Er-f~LR9Q28TQl6~vYEUsWZQ0f2wyAfSERV7H8oZmBm1yG~eWv2Ep-lihe6FP6KIASIaciyI99n6IPKM-MdfN7NpYESzxK6Kp9UV8rMUxBj2gPvQzmFz3Eo9UD9HOcSwhSidds5HhmOPZSB2V4uFZ8N5Rp5lvUd9a2Rnzoq1iFCssMFGdH4ybDK6Ma18B68YmYUj9CLu4l99zyV04m~JvlCYL2JqdCrIPaU67Cvc6P9oPk4Zwy7-jdH-bCLvsx9XF0d0Xy4tOYieW7eNBME3u-Ooyn9jcoEA0OYSDbCjynQr20pJLWJaiesU6OixLItwQYDbhTaQGg__&Key-Pair-Id=APKAIE5G5CRDK6RD3PGA
  tags:
  - budding yeast

- id: doi:10.1083/jcb.201701061
  my_comment: CAM histone paper, 2017
  description: Chromosomes replicate in a characteristic and reproducible temporal order. However, it has been unknown whether there is a physiological requirement for the regulation of replication timing. In this paper, we report our discovery that early DNA replication is required for the highest expression levels of certain genes.<br>[Highlighted](http://jcb.rupress.org/content/216/7/1869) in J. Cell Biol. by María Gómez, selected for the [Nuclear biology special collection](http://jcb.rupress.org/cc/nuclear-organization-and-function) by Ana Pombo and selected for the [DNA replication and genome instability special collection](http://jcb.rupress.org/cc/dna-replication-and-genome-instability?vsmaid=3951&vcid=20955) by Agata Smogorzewska.<br>Selected as “of outstanding interest” by Mirit Aladjem and colleagues in their [Current Opinion in Cell Biology review](http://sciencedirect.com/science/article/pii/S0955067417300522).
  tags:
  - budding yeast
  - comparative genomics

- id: doi:10.1126/science.aaf4791
  my_comment: synII, 2017
  image: images/Sc2.0_logo.png
  tags:
  - budding yeast
  - synthetic biology

- id: doi:10.1007/978-3-319-24696-3_6
  my_comments: 2016 review
  tags:
  - review

- id: doi:10.1016/j.cub.2015.06.023
  my_comment: CEN with Tomo & Ken, 2015
  tags:
  - comparative genomics
  - budding yeast

- id: doi:10.1038/nsmb.2962
  my_comment: Pu-seq paper with Tony, 2015
  description: This collaborative study reveals that polymerase epsilon is responsible for leading strand synthesis, with polymerase delta undertaking lagging strand synthesis. Our polymerase usage data directly maps replication origin location, quantifies origin efficiency, reveals that replication termination events are dispersed across large termination zones and indirectly estimates replication timing.<br>With associated [News & Views](https://www.nature.com/articles/nsmb.2981) by Sue Jinks-Robertson & Hannah L Klein.
  image: images/replication-fork-polymerases.png
  tags:
  - fission yeast
  - new method

- id: doi:10.1093/nar/gkt878
  my_comment: NAR HTS methods paper, 2013
  description: This paper describes and rigorously validates a range of next generation sequencing approaches to reveal at unprecedented resolution the temporal order of genome replication. My research group and others are applying these sequencing approaches to a range of questions in a variety of organisms.
  image: images/24089142.jpg
  tags:
  - new method
  - budding yeast

- id: doi:10.1016/j.celrep.2013.10.014
  my_comment: MH and RR modelling paper, 2013
  description: In this study we used a combination of high-resolution, genomic-wide DNA replication data, mathematical modelling and single cell experiments to reveal the stochastic nature of replication initiation and termination. We find that the homogeneous picture implied by ensemble datasets masks biologically significant cell-to-cell variation in genome replication.
  image: images/24210825.jpg
  tags:
  - mathematical modelling
  - budding yeast

- id: doi:10.1093/nar/gkt728
  my_comment: ori distribution with JJB, 2013
  image: images/blow&newman.png
  tags:
  - mathematical modelling
  - budding yeast

- id: doi:10.1016/j.molcel.2013.05.011
  my_comment: Mol Cell, 2013, CEN replication timing paper
  description: We discovered that kinetochore recruitment of the Dbf4-dependent kinase ensures early centromere replication. Mutations that delay centromere replication give rise to elevated chromosome loss, revealing the first physiological role for temporal regulation of genome replication.<br>This work is recommended in [F1000](https://connect.h1.co/pubmed/23746350).
  image: https://www.cell.com/cms/attachment/142c9086-4235-4f40-9132-2b468b17f63f/fx1_lrg.jpg
  tags:
   - budding yeast

- id: doi:10.1038/nature12650
  my_comment: H. volcanii nature paper, 2013
  description: We discovered that the halophilic archaea, Haloferax volcanii, not only can survive in the absence of DNA replication origins, but also has accelerated growth.<br>This work is recommended in F1000 and featured in a [research highlight](https://www.nature.com/articles/nrmicro3177) in Nature Reviews Microbiology.<br>See associated article at [The Conversation](https://theconversation.com/selfish-gene-solves-dna-replication-puzzle-20166).
  image: images/Hv_replication.png
  tags:
   - archaea

- id: doi:10.1083/jcb.201306143
  my_comment: TT paper replicon clusters, 2013
  tags:
   - budding yeast
   - mathematical modelling

- id: doi:10.1371/journal.pgen.1003798
  my_comment: CAF ORC binding, 2013
  image: https://journals.plos.org/plosgenetics/article/figure/image?download&size=large&id=10.1371/journal.pgen.1003798.g001
  tags:
   - budding yeast

- id: doi:10.1038/nature12312
  my_comment: RL E. coli, 2013
  tags:
   - E. coli

- id: doi:10.1186/1471-2164-14-69
  my_comment: Sa assembly, 2013
  tags:
   - budding yeast
   - genome assembly

- id: doi:10.1103/PhysRevE.86.031916
  my_comment: PRE paper, 2012
  image: images/23030953.jpg
  tags:
  - mathematical modelling

- id: doi:10.1101/gr.139477.112
  my_comment: CAM sensu stricto, 2012
  description: We found that the temporal order of genome replication is conserved between species. The discovery of a minority of DNA replication origins that have evolved different activities allowed us to demonstrate that origin activity is locally (cis) regulated.
  image: images/Müller_Fig_3_panel.png
  tags:
   - comparative genomics
   - budding yeast

- id: doi:10.1093/nar/gkq343
  my_comment: NAR modelling paper
  description: We present a mathematical model for whole chromosome replication, conceptualising how key molecular properties of DNA replication are related and demonstrating the wealth of information available in quantitative genomic datasets.<br>This work is recommended in F1000.
  tags:
    - mathematical modelling

- id: doi:10.1093/nar/gkl758
  my_comment: original OriDB paper
  description: This paper presents the DNA replication origin database, OriDB, a catalogue of confirmed and predicted DNA replication origin sites. This database is an example of our commitment not only to sharing data, but also to making it highly accessible to the research community – see links on the resources page.

- id: doi:10.1101/gad.385306
  my_comment: G&D comparative genomics, 2006
  description: This was the first paper to use comparative genomics to investigate DNA replication. We discovered that the functional sequence elements at DNA replication origins are evolutionarily conserved, leaving a phylogenetic footprint that allowed them to be pin- pointed genome-wide.<br>This work is recommended in F1000.
  image: images/ori_conservation.png
  tags:
   - comparative genomics
   - budding yeast
   - new method

- id: doi:10.1186/gb-2002-3-12-research0070
  my_comment: Genome Biology PhD paper, 2002
  title: Whole-genome analysis of animal A- and B-type cyclins
  tags:
   - comparative genomics

- id: doi:10.1186/gb-2001-2-12-reports4030
  my_comment: Genome Biology meeting report, 2001
  title: 'Chromosome replication: from ORC to fork'
  date: 2001-01-01
  image: https://images.app.goo.gl/HGD4ktaRioNTGdDF7
  tags:
   - review
